### ISSUE TITLE
Question regarding your decision to stop working on this

### ISSUE THREAD

**Issue by Michael-K-GH** [rminderhoud/rose-godot#1]
You mentioned that you found Godot to not be a good fit for this project. Can you explain what caused you to come to this conclusion? I've been thinking about remaking the client myself, and I'm familiar with Godot, so I thought I might give that a try. I'd like to know what kind of problems you encountered, though.

**Comment by rminderhoud** [comment]
Hi @Michael-Kelley, well if you do decide to work on a new client for ROSE there will surely be people interested in contributing. We have a discord channel and I know of at least one person who has wanted to work on such a client and he even wanted to build it in godot! Here's a link if you're interested https://discord.gg/GdK3yJ.

Regarding my time with godot, I loved the engine but there were too many rough edges for me in building a 3D game that I decided to stop. It seriously dissappoints me because it is such a great engine in so many ways but falls just short of being usable for professional-grade 3D game development. It has been a while and things might have changed since my last foray but I've done my best to summarize my issues:

- Poor performance due to lack of optimizations in the 3d renderer (e.g. LOD, occlusion, etc.). This may have improved over time but it's hard to say because also over the course of my experiments they kept rewriting their rendering engines so can't really compare their performance over time. I believe this is still an issue today. I got demotivated waiting for improvements, especially when all the improvement effort was going to vulkan which is still not universally supported on all machines.
- Editor tooling for navigating and interacting with 3d objects was not particularly fluid. E.g. moving items around the scene, rotating them, snapping to other items/grids, etc. etc.
- The animation system got some improvements during my usage but there were still some usability issues that made it tedious to experiment with animations (e.g. related to resetting animations, viewing T-poses, etc.)
- No native support for heightmap or other terrain element meant I had to roll my own. Due to the overall performance of the engine this was a bigger task than I wanted to tackle.
- I believe this was fixed but the editor did not handle the volume of ROSE assets that well. If you combine all the textures, meshes, animations, etc. the number of files goes into the thousands. There was some edge cases where the editor did not handle that many files well and it slowed down some operations such as when it would decide it needed to re-import/re-scan all the assets again. I think I filed a bug about it breaking the text editor or file explorer or something like that.
- Lighting engine wasn't very good with some weird artifacts but ROSE already has pre-baked lightmaps so I could work around it. Although it would have been nice to switch to the engine's lighting. The lightmap functionality was squeezed in at the last minute in the release I was using but it was still too new for me to use it.
- The export templates were not working for me because I needed to use the master branch to stay up to date with the 3d graphics changes and they were not maintained as closely with all the changes going on (justifiably). Meant that the game was working fine in the editor but the ability to "release" the client was dubious during my development.

Overall, these are all nitpicks and most of these things can be worked around. In the end, the one thing that frustrated me was the culture surrounding the development of Godot. Building a game (or game client for an MMO!) can be a multi-month, multi-year commitment. For me this meant that I would want to be sure that by the time I was finished building my parts that I would be able to release my client/game. While I was doing my development, there was a heavy stream of new feature development from Godot and a big focus by the main developers on these new features. The regular maintenance and improvements were left to the community to fix themselves. New features were prioritized at the cost of improving the existing features and more than once it felt as though the new features were released with great ceremony and pomp only to not be fully fleshed out and left to the community to take over and improve. This did not give me confidence in the long-term viability of my project within Godot as the project could (and did!) shift under my feet in the name of new feature development. For example, they dropped the GLES renderer in favor of vulkan and then went back and added a GLES renderer again! The project is too fluid to ship a large, complex game and as such I don't think it's viable as an engine for this kind of project since the development timeline is so long.

So in the end, Godot wasn't a good fit for *ME* and *this project* at the time and I wasn't confident it would be a good fit for the project over my intended timeline. I still believe it's good engine as long as you can look at its current version, assume nothing will be added and can easily say "this will fit my needs". I hope that with Godot 4 they might finally stop chasing the rabbit and buckle down on polishing things up on the 3D side but I am not optimistic :). It's truly a shame because I *thoroughly* enjoyed *using* the engine but alas, I also wanted to ship something in the end and did not feel that Godot would help me do that.

**Comment by Michael-K-GH** [comment]
Thank you for the detailed response. I do agree with some points, and I also have some of my own gripes with the current state of Godot. However, I really like it as a whole. Being completely open-source is a huge benefit, too. Hopefully, by the time I start working on the client, Godot 4.0 will at least have a beta out.
